# Generated by Django 6.0.6 on 2026-06-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionb', models.TextField()),
                ('answer', models.TextField()),
                ('grammar_score', models.FloatField(default=0)),
                ('relevance_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('grammar_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
